version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    schedule:
      interval: "daily"

